// samples/core/vue-sample/src/App.vue
<template>
  <div class="app">
    <header>
      <img src="./assets/logo.png" class="logo" alt="Vonage" />
      <h1>Video API Accelerator Core</h1>
    </header>
    <article>
      <main class="app-video-container">
        <div v-if="!connected" className="app-mask">
          <!-- <Spinner /> -->
          <div className="message with-spinner">Connecting</div>
        </div>
        <div v-if="connected && !active" className="app-mask">
          <button
            className="message button clickable"
            @click.prevent="startCall"
          >
            Click to Start Call
          </button>
        </div>
        <div id="cameraPublisherContainer" class="{cameraPublisherClass}" />
        <div id="screenPublisherContainer" class="{screenPublisherClass}" />
        <div id="cameraSubscriberContainer" class="{cameraSubscriberClass}" />
        <div id="screenSubscriberContainer" class="{screenSubscriberClass}" />
      </main>
      <section v-if="active" id="controls">
        <div
          class="audio"
          v-bind:class="{ muted: !localAudioEnabled }"
          @click.prevent="toggleLocalAudio"
        />
        <div
          class="video"
          v-bind:class="{ muted: !localVideoEnabled }"
          @click.prevent="toggleLocalVideo"
        />
        <div class="end-call" @click.prevent="endCall" />
      </section>
      <aside id="chat" />
    </article>
  </div>
</template>

<script>
import config from './config.json';

const otCoreOptions = {
  credentials: {
    apiKey: config.apiKey,
    sessionId: config.sessionId,
    token: config.token
  },
  // A container can either be a query selector or an HTML Element
  streamContainers(pubSub, type) {
    return {
      publisher: {
        camera: '#cameraPublisherContainer',
        screen: '#screenPublisherContainer'
      },
      subscriber: {
        camera: '#cameraSubscriberContainer',
        screen: '#screenSubscriberContainer'
      }
    }[pubSub][type];
  },
  controlsContainer: '#controls',
  packages: [],
  communication: {
    callProperites: null // Using default
  },
  textChat: {
    name: ['David', 'Paul', 'Emma', 'George', 'Amanda'][
      (Math.random() * 5) | 0
    ], // eslint-disable-line no-bitwise
    waitingMessage: 'Messages will be delivered when other users arrive',
    container: '#chat'
  },
  screenSharing: {
    extensionID: config.extensionID,
    annotation: true,
    externalWindow: false,
    dev: true,
    screenProperties: {
      insertMode: 'append',
      width: '100%',
      height: '100%',
      showControls: false,
      style: {
        buttonDisplayMode: 'off'
      },
      videoSource: 'window',
      fitMode: 'contain' // Using default
    }
  },
  annotation: {
    absoluteParent: {
      publisher: '.app-video-container',
      subscriber: '.app-video-container'
    }
  }
};

export default {
  name: 'app',
  data() {
    return {
      active: false,
      connected: false,
      localAudioEnabled: true,
      localVideoEnabled: true,
      otCore: null
    };
  },
  mounted() {
    this.otCore = new AccCore(otCoreOptions);
    this.otCore.connect().then(() => (this.connected = true));
  },
  methods: {
    startCall() {
      this.otCore
        .startCall()
        .then(() => {
          this.active = true;
        })
        .catch((error) => console.log(error));
    },
    endCall() {
      this.otCore.endCall();
      this.active = false;
    },
    toggleLocalAudio() {
      this.otCore.toggleLocalAudio(!this.localAudioEnabled);
      this.localAudioEnabled = !this.localAudioEnabled;
    },
    toggleLocalVideo() {
      this.otCore.toggleLocalVideo(!this.localVideoEnabled);
      this.localVideoEnabled = !this.localVideoEnabled;
    }
  }
};
</script>

<style>
html,
body {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: sans-serif;
}
*,
*:before,
*:after {
  box-sizing: inherit;
}

header {
  background-color: #000;
  height: 40px;
  color: white;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 20px;
}

header h1 {
  font-size: 16px;
  font-weight: 200;
}

header .logo {
  height: 60%;
  width: auto;
}

article {
  position: relative;
  width: 75vw;
  height: calc(75vw * 0.6);
  margin: 10px auto;
  border: 1px solid lightblue;
}

#controls {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto;
}

#controls div {
  width: 50px;
  height: 50px;
  margin: 20px 0 !important;
  border: 2px solid white;
  border-radius: 50%;
  background-position: center;
  background-color: rgba(27, 134, 144, 0.4);
  background-color: lightgrey;
  background-repeat: no-repeat;
  cursor: pointer;
}

#controls div.audio {
  background-image: url(https://assets.tokbox.com/solutions/images/icon-mic.png);
}

#controls div.audio:hover,
#controls div.audio.muted {
  background-image: url(https://assets.tokbox.com/solutions/images/icon-muted-mic.png);
}

#controls div.video {
  background-image: url(https://assets.tokbox.com/solutions/images/icon-video.png);
}

#controls div.video.muted {
  background-image: url(https://assets.tokbox.com/solutions/images/icon-no-video.png);
}

#controls div.end-call {
  background-image: url(https://assets.tokbox.com/solutions/images/icon-hang-up.png);
  background-color: red;
}

main {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}

main .video-container {
  width: 100%;
  height: 100%;
  display: flex;
}

main .video-container.small {
  position: absolute;
  top: 20px;
  right: 20px;
  width: 160px;
  height: 96px;
  border: 1px solid #fcba00;
  z-index: 2;
}

main .video-container.small.left {
  left: 20px;
  border: 1px solid #00fcc2;
}

main .video-container.hidden {
  display: none;
}

main .video-container.active-gt2 {
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
  height: 100%;
  width: 100%;
}

main .video-container.active-gt2.hidden {
  display: none;
}

main .video-container.active-gt2 .OT_subscriber {
  margin: 0;
  padding: 0;
  display: inline-block;
  font-size: 0;
  flex-basis: 50%;
  box-sizing: border-box;
  width: auto !important;
  height: auto !important;
}

main .video-container.active-gt2.active-odd .OT_subscriber:first-child {
  flex-basis: 100%;
}

.app-mask {
  width: 100%;
  height: 100%;
  position: relative;
  color: white;
  background: rgba(27, 134, 144, 0.4);
  display: flex;
  justify-content: center;
  align-items: center;
}

.app-mask .react-spinner {
  position: absolute;
}

.app-mask .message {
  font-weight: 200;
}

.app-mask .message.with-spinner {
  position: absolute;
  top: 55%;
}

.app-mask .message.button {
  border: 1px solid white;
  padding: 20px 40px;
  border-radius: 6px;
  background-color: Transparent;
  color: white;
  font-family: sans-serif;
  font-size: medium;
}

.app-mask .message.button:focus:active,
.message.button:focus,
.message.button:active {
  background-image: none;
  outline: none;
  -webkit-box-shadow: none;
  box-shadow: none;
}
</style>

// js/react-sample-app/src/App.js
/* eslint-disable */
/* Let CRA handle linting for sample app */
import React, { Component } from 'react';
import Spinner from 'react-spinner';
import classNames from 'classnames';
import logo from './logo.svg';
import otCore from './ot-core/core.js';
import config from './config.json';
import './App.css';
import 'opentok-solutions-css';

const otCoreOptions = {
  credentials: {
    apiKey: config.apiKey,
    sessionId: config.sessionId,
    token: config.token,
  },
  // A container can either be a query selector or an HTML Element
  streamContainers(pubSub, type, data){
    return {
      publisher: {
        camera: '#cameraPublisherContainer',
        screen: '#screenPublisherContainer',
      },
      subscriber: {
        camera: '#cameraSubscriberContainer',
        screen: '#screenSubscriberContainer',
      },
    }[pubSub][type];
  },
  controlsContainer: '#controls',
  packages: ['textChat', 'screenSharing', 'annotation', 'archiving'],
  communication: {
    callProperites: null, // Using default
  },
  textChat: {
    name: ['David', 'Paul', 'Emma', 'George', 'Amanda'][Math.random() * 5 | 0],
    waitingMessage: 'Messages will be delivered when other users arrive',
    container: '#chat',
  },
  screenSharing: {
    extensionID: 'plocfffmbcclpdifaikiikgplfnepkpo',
    annotation: true,
    externalWindow: false,
    dev: true,
    screenProperties: {
      insertMode: 'append',
      width: '100%',
      height: '100%',
      showControls: false,
      style: {
        buttonDisplayMode: 'off',
      },
      videoSource: 'window',
      fitMode: 'contain' // Using default
    },
  },
  annotation: {
    absoluteParent: {
      publisher: '.App-video-container',
      subscriber: '.App-video-container'
    }
  },
  archiving: {
    startURL: 'https://example.com/startArchive',
    stopURL: 'https://example.com/stopArchive',
  },
};

/**
 * Build classes for container elements based on state
 * @param {Object} state
 */
const containerClasses = (state) => {
  const { active, meta, localAudioEnabled, localVideoEnabled } = state;
  const sharingScreen = meta ? !!meta.publisher.screen : false;
  const viewingSharedScreen = meta ? meta.subscriber.screen : false;
  const activeCameraSubscribers = meta ? meta.subscriber.camera : 0;
  return {
    controlClass: classNames('App-control-container', { 'hidden': !active }),
    localAudioClass: classNames('ots-video-control circle audio', { 'muted': !localAudioEnabled }),
    localVideoClass: classNames('ots-video-control circle video', { 'muted': !localVideoEnabled }),
    cameraPublisherClass: classNames('video-container', { 'hidden': !active, 'small': !!activeCameraSubscribers || sharingScreen, 'left': sharingScreen || viewingSharedScreen }),
    screenPublisherClass: classNames('video-container', { 'hidden': !sharingScreen }),
    cameraSubscriberClass: classNames('video-container', { 'hidden': !activeCameraSubscribers },
      `active-${activeCameraSubscribers}`, { 'small': viewingSharedScreen || sharingScreen }
    ),
    screenSubscriberClass: classNames('video-container', { 'hidden': !viewingSharedScreen }),
  };
};

const connectingMask = () =>
  <div className="App-mask">
    <Spinner />
    <div className="message with-spinner">Connecting</div>
  </div>;

const startCallMask = start =>
  <div className="App-mask">
    <div className="message button clickable" onClick={start}>Click to Start Call</div>
  </div>;

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      connected: false,
      active: false,
      publishers: null,
      subscribers: null,
      meta: null,
      localAudioEnabled: true,
      localVideoEnabled: true,
    };
    this.startCall = this.startCall.bind(this);
    this.toggleLocalAudio = this.toggleLocalAudio.bind(this);
    this.toggleLocalVideo = this.toggleLocalVideo.bind(this);
  }

  componentDidMount() {
    otCore.init(otCoreOptions);
    otCore.connect().then(() => this.setState({ connected: true }));
    const events = [
      'subscribeToCamera',
      'unsubscribeFromCamera',
      'subscribeToScreen',
      'unsubscribeFromScreen',
      'startScreenShare',
      'endScreenShare',
    ];

    events.forEach(event => otCore.on(event, ({ publishers, subscribers, meta }) => {
      this.setState({ publishers, subscribers, meta });
    }));
  }

  startCall() {
    this.setState({ active: true });
    otCore.startCall()
      .then(({ publishers, subscribers, meta }) => {
        this.setState({ publishers, subscribers, meta });
      }).catch(error => console.log(error));
  }

  toggleLocalAudio() {
    otCore.toggleLocalAudio(!this.state.localAudioEnabled);
    this.setState({ localAudioEnabled: !this.state.localAudioEnabled });
  }

  toggleLocalVideo() {
    otCore.toggleLocalVideo(!this.state.localVideoEnabled);
    this.setState({ localVideoEnabled: !this.state.localVideoEnabled });
  }

  render() {
    const { connected, active } = this.state;
    const {
      localAudioClass,
      localVideoClass,
      controlClass,
      cameraPublisherClass,
      screenPublisherClass,
      cameraSubscriberClass,
      screenSubscriberClass,
    } = containerClasses(this.state);

    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1>OpenTok Accelerator Core</h1>
        </div>
        <div className="App-main">
          <div id="controls" className={controlClass}>
            <div className={localAudioClass} onClick={this.toggleLocalAudio}></div>
            <div className={localVideoClass} onClick={this.toggleLocalVideo}></div>
          </div>
          <div className="App-video-container">
            { !connected && connectingMask() }
            { connected && !active && startCallMask(this.startCall)}
            <div id="cameraPublisherContainer" className={cameraPublisherClass}></div>
            <div id="screenPublisherContainer" className={screenPublisherClass}></div>
            <div id="cameraSubscriberContainer" className={cameraSubscriberClass}></div>
            <div id="screenSubscriberContainer" className={screenSubscriberClass}></div>
          </div>
          <div id="chat" className="App-chat-container"></div>
        </div>
      </div>
    );
  }
}

export default App;
